data:
  train: ./data/gazeta_train.jsonl
  test: ./data/gazeta_test.jsonl

model:
  seed: 42
  num_workers: 10
  name: my_model
  dirpath: checkpoints
  filename: best-checkpoint
  model_name: IlyaGusev/rut5_base_sum_gazeta
  tokenizer_name: IlyaGusev/rut5_base_sum_gazeta
  text_max_token_len: 512
  summary_max_token_len: 128
  lr: 1e-3
  eps: 1e-5

training:
  batch_size: 7
  epochs: 1
  devices: 1
  accelerator: gpu
  precision: bf16-mixed
  log_every_n_steps: 5
  save_top_k: 1
  monitor: val_loss
  mode: min
  logger_name: news-summary
  logger_folder: lightning_logs


mlflow:
  uri: http://localhost:13412/
  experiment_name: lightning_logs